import{t as e}from"../page-oXuJ.js";const t=new e(async function({},e){return document.title=`Loops | Nijor`,`<section n-scope="tcne9"><h1 n-scope="tcne9">Loops</h1><p n-scope="tcne9"> Nijor provides a simple way to render repeated content using the <span class="txt" n-scope="tcne9">n:loop</span> attribute. Loops are useful when you want to render a list of items from an array. <br n-scope="tcne9"> A loop must be declared on a parent element. This is usually a <span class="txt" n-scope="tcne9">div</span>, but any suitable element can be used. You can't add <span class="txt" n-scope="tcne9">id</span> attribute to the element. <br n-scope="tcne9"> The <span class="txt" n-scope="tcne9">n:loop</span> attribute works together with two other attributes : <span class="txt" n-scope="tcne9">source</span> and <span class="txt" n-scope="tcne9">var</span>. <br n-scope="tcne9"><span class="txt" n-scope="tcne9">source</span> refers to the array variable defined in <span class="txt" n-scope="tcne9">script</span>, and <span class="txt" n-scope="tcne9">var</span> defines the variable name used for each item during iteration. </p></section><section n-scope="tcne9"><h1 n-scope="tcne9">Example</h1> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">import</span><span style="color:#9CDCFE"> name</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"house"</span><span style="color:#9CDCFE"> source</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"@/components/houses.nijor"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">div</span><span style="color:#9CDCFE"> n:loop</span><span style="color:#9CDCFE"> var</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"x"</span><span style="color:#9CDCFE"> source</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"houses"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">house</span><span style="color:#9CDCFE"> name</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{x.name}"</span><span style="color:#9CDCFE"> rent</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"₹{x.rent}"</span><span style="color:#9CDCFE"> location</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{x.location}"</span><span style="color:#808080">&gt;&lt;/</span><span style="color:#569CD6">house</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;/</span><span style="color:#569CD6">div</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#569CD6">            const</span><span style="color:#9CDCFE"> houses</span><span style="color:#D4D4D4"> = [</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name :</span><span style="color:#CE9178"> "The Sky Mansion"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 62000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Hengrabari, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name :</span><span style="color:#CE9178"> "The Octagon Mansion"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 30000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Ganeshguri, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name :</span><span style="color:#CE9178"> "The Dragon Palace"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 45000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Chacal, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">            ];</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code></section><section n-scope="tcne9"><h1 n-scope="tcne9">With Reactive Source</h1> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">import</span><span style="color:#9CDCFE"> name</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"house"</span><span style="color:#9CDCFE"> source</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"@/components/houses.nijor"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">div</span><span style="color:#9CDCFE"> n:loop</span><span style="color:#9CDCFE"> var</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"x"</span><span style="color:#9CDCFE"> source</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"$.houses"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">house</span><span style="color:#9CDCFE"> name</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{x.name}"</span><span style="color:#9CDCFE"> rent</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"₹{x.rent}"</span><span style="color:#9CDCFE"> location</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{x.location}"</span><span style="color:#808080">&gt;&lt;/</span><span style="color:#569CD6">house</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;/</span><span style="color:#569CD6">div</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">button</span><span style="color:#9CDCFE"> on:click</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"more()"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Load More</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">button</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#9CDCFE">            $</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">houses</span><span style="color:#D4D4D4"> = [</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name :</span><span style="color:#CE9178"> "The Sky Mansion"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 62000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Hengrabari, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name :</span><span style="color:#CE9178"> "The Octagon Mansion"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 30000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Ganeshguri, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name :</span><span style="color:#CE9178"> "The Dragon Palace"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 45000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Chacal, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">            ];</span></span>
<span class="line"></span>
<span class="line"><span style="color:#569CD6">            async</span><span style="color:#569CD6"> function</span><span style="color:#DCDCAA"> more</span><span style="color:#D4D4D4">(</span><span style="color:#9CDCFE">$</span><span style="color:#D4D4D4">){</span></span>
<span class="line"><span style="color:#569CD6">                const</span><span style="color:#9CDCFE"> moreHouses</span><span style="color:#D4D4D4"> = </span><span style="color:#C586C0">await</span><span style="color:#DCDCAA"> fetch</span><span style="color:#D4D4D4">(...);</span></span>
<span class="line"><span style="color:#9CDCFE">                $</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">houses</span><span style="color:#D4D4D4"> = [... </span><span style="color:#9CDCFE">$</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">houses</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">moreHouses</span><span style="color:#D4D4D4">]; </span><span style="color:#6A9955">// The entire loop would be rerendered, even those entries which didn't change</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code></section>`},async function({},e){},`docs`);export{t as default};