import{t as e}from"../page-KpEe.js";const t=new e(async function({},e){return document.title=`Plugins | Nijor`,`<section n-scope="mq3vm"><h1 n-scope="mq3vm">Plugins</h1><p n-scope="mq3vm">Plugins in Nijor let you define custom behavior at compile time. Many built-in features such as <span class="txt" n-scope="mq3vm">n:loop</span>, <span class="txt" n-scope="mq3vm">on:event</span>, and reactive variables are internally powered by plugins, making Nijor flexible and modular.</p></section><section n-scope="mq3vm"><h1 n-scope="mq3vm">Using Plugins</h1><p n-scope="mq3vm">Before creating your own plugins, you can use existing ones by importing them into <span class="txt" n-scope="mq3vm">nijor.config.js</span> and adding them to the <span class="txt" n-scope="mq3vm">plugins</span> array.</p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#9CDCFE"> plugin1</span><span style="color:#C586C0"> from</span><span style="color:#CE9178"> "@/plugins/plugin1.js"</span></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#9CDCFE"> plugin2</span><span style="color:#C586C0"> from</span><span style="color:#CE9178"> "@/plugins/plugin2.js"</span></span>
<span class="line"></span>
<span class="line"><span style="color:#C586C0">        export</span><span style="color:#569CD6"> const</span><span style="color:#9CDCFE"> plugins</span><span style="color:#D4D4D4"> =</span><span style="color:#E6E6E6"> [ </span><span style="color:#DCDCAA">plugin1</span><span style="color:#E6E6E6">(), </span><span style="color:#DCDCAA">plugin2</span><span style="color:#E6E6E6">() ];</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="mq3vm">Nijor will run these plugins during compilation in the order they appear in the array.</p></section><section n-scope="mq3vm"><h1 n-scope="mq3vm">Plugin Development</h1><p n-scope="mq3vm">A Nijor plugin exports a default async function. This function receives a single object containing <span class="txt" n-scope="mq3vm">document</span>, <span class="txt" n-scope="mq3vm">scope</span>, <span class="txt" n-scope="mq3vm">props</span>, <span class="txt" n-scope="mq3vm">scripts</span>, <span class="txt" n-scope="mq3vm">filename</span>, and <span class="txt" n-scope="mq3vm">module_type</span>.</p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        export</span><span style="color:#569CD6"> async</span><span style="color:#569CD6"> function</span><span style="color:#DCDCAA"> plugin</span><span style="color:#E6E6E6">(</span><span style="color:#9CDCFE">properties</span><span style="color:#E6E6E6">){</span></span>
<span class="line"></span>
<span class="line"><span style="color:#C586C0">            return</span><span style="color:#569CD6"> async</span><span style="color:#569CD6"> function</span><span style="color:#E6E6E6"> ({ </span><span style="color:#9CDCFE">document</span><span style="color:#E6E6E6">, </span><span style="color:#9CDCFE">scope</span><span style="color:#E6E6E6">, </span><span style="color:#9CDCFE">props</span><span style="color:#E6E6E6">, </span><span style="color:#9CDCFE">scripts</span><span style="color:#E6E6E6">, </span><span style="color:#9CDCFE">filename</span><span style="color:#E6E6E6">, </span><span style="color:#9CDCFE">module_type</span><span style="color:#E6E6E6"> }) {</span></span>
<span class="line"><span style="color:#6A9955">                // Plugin logic</span></span>
<span class="line"></span>
<span class="line"><span style="color:#C586C0">                return</span><span style="color:#E6E6E6"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                    name:</span><span style="color:#CE9178"> "Plugin Name"</span><span style="color:#E6E6E6">,</span></span>
<span class="line"><span style="color:#9CDCFE">                    body:</span><span style="color:#9CDCFE"> document</span><span style="color:#E6E6E6">.</span><span style="color:#9CDCFE">body</span><span style="color:#E6E6E6">.</span><span style="color:#9CDCFE">innerHTML</span><span style="color:#E6E6E6">,</span></span>
<span class="line"><span style="color:#D4D4D4">                    ...</span><span style="color:#9CDCFE">scripts</span></span>
<span class="line"><span style="color:#E6E6E6">                };</span></span>
<span class="line"><span style="color:#E6E6E6">            }</span></span>
<span class="line"><span style="color:#E6E6E6">        </span></span>
<span class="line"><span style="color:#E6E6E6">        }</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><h1 n-scope="mq3vm">Plugin Arguments</h1><p n-scope="mq3vm">The plugin function receives the parsed <span class="txt" n-scope="mq3vm">document</span>, the current <span class="txt" n-scope="mq3vm">scope</span>, component <span class="txt" n-scope="mq3vm">props</span>, the generated <span class="txt" n-scope="mq3vm">scripts</span> object, the current <span class="txt" n-scope="mq3vm">filename</span>, and the <span class="txt" n-scope="mq3vm">module_type</span>.</p><p n-scope="mq3vm">The <span class="txt" n-scope="mq3vm">module_type</span> can be component, layout, page.</p><p n-scope="mq3vm">The <span class="txt" n-scope="mq3vm">scope</span> is a random string unique to a particular component, layout or page.</p><p n-scope="mq3vm">The <span class="txt" n-scope="mq3vm">scripts</span> object contains three properties: <span class="txt" n-scope="mq3vm">main</span>, <span class="txt" n-scope="mq3vm">global</span>, and <span class="txt" n-scope="mq3vm">defer</span>.</p><p n-scope="mq3vm">Do not overwrite <span class="txt" n-scope="mq3vm">scripts.main</span> directly unless absolutely necessary. Prefer appending to it instead :</p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#9CDCFE">        scripts</span><span style="color:#E6E6E6">.</span><span style="color:#9CDCFE">main</span><span style="color:#D4D4D4"> +=</span><span style="color:#CE9178"> "// additional code"</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="mq3vm">Since these fields contain generated script code, replacing them carelessly may break compilation output.</p><h2 n-scope="mq3vm">Internal Compilation</h2><p n-scope="mq3vm">Internally, a <span class="txt" n-scope="mq3vm">.nijor</span> file is compiled into a structure similar to this:</p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#6A9955">        // scripts.global</span></span>
<span class="line"><span style="color:#569CD6">        const</span><span style="color:#9CDCFE"> x</span><span style="color:#D4D4D4"> =</span><span style="color:#569CD6"> new</span><span style="color:#DCDCAA"> component</span><span style="color:#E6E6E6">(</span><span style="color:#9CDCFE">templateFn</span><span style="color:#E6E6E6">, </span><span style="color:#9CDCFE">callbackFn</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="mq3vm"><span class="txt" n-scope="mq3vm">scripts.global</span> contains top-level code such as component initialization. <span class="txt" n-scope="mq3vm">templateFn</span> returns the template output. Code written inside the <span class="txt" n-scope="mq3vm">&lt;script&gt;</span> tag is placed inside <span class="txt" n-scope="mq3vm">templateFn</span>, except for imports, which are moved to the top level. <span class="txt" n-scope="mq3vm">callbackFn</span> runs immediately after <span class="txt" n-scope="mq3vm">templateFn</span> renders the template, including child component rendering. <span class="txt" n-scope="mq3vm">scripts.defer</span> is injected inside <span class="txt" n-scope="mq3vm">templateFn</span>.</p></section>`},async function({},e){},`docs`);export{t as default};