import{a as e}from"../main.js";const t=new e(async function({},e){return document.title=`Routing | Nijor`,`<section n-scope="mjsl2"><h1 n-scope="mjsl2">Routing in Nijor</h1><p n-scope="mjsl2"> Nijor utilizes a modern <strong n-scope="mjsl2">file-based routing system</strong>. Routes are automatically generated based on the file and folder hierarchy located inside the <span class="txt" n-scope="mjsl2">src/pages</span> directory. Each <span class="txt" n-scope="mjsl2">.nijor</span> file inside this folder compiles into a distinct application route. </p><p n-scope="mjsl2"> This declarative, convention-over-configuration model eliminates the need to manually register, configure, or maintain a centralized routing file. </p></section><section n-scope="mjsl2"><h1 n-scope="mjsl2">Basic Routing</h1><p n-scope="mjsl2"> Every standard file in the <span class="txt" n-scope="mjsl2">src/pages</span> directory maps directly to a URL route path: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"><span></span></span>
<span class="line"><span>        src/pages/</span></span>
<span class="line"><span>            index.nijor</span></span>
<span class="line"><span>            about.nijor</span></span>
<span class="line"><span>    </span></span></code></pre></code><p n-scope="mjsl2"> This structure generates the following URL endpoints: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"><span></span></span>
<span class="line"><span>        index.nijor  -&gt; / (Home Page)</span></span>
<span class="line"><span>        about.nijor  -&gt; /about</span></span>
<span class="line"><span>    </span></span></code></pre></code><p n-scope="mjsl2"> If a visitor navigates to a URL that does not map to a page, Nijor will automatically render the fallback error page located at <span class="txt" n-scope="mjsl2">src/pages/404.nijor</span>. </p></section><section n-scope="mjsl2"><h1 n-scope="mjsl2">Nested Routing</h1><p n-scope="mjsl2"> Creating subdirectories inside <span class="txt" n-scope="mjsl2">src/pages</span> naturally organizes your application into nested paths and route structures: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"><span></span></span>
<span class="line"><span>        src/pages/</span></span>
<span class="line"><span>            blog/</span></span>
<span class="line"><span>                index.nijor</span></span>
<span class="line"><span>                [slug].nijor</span></span>
<span class="line"><span>    </span></span></code></pre></code><p n-scope="mjsl2"> This directory structure compiles into the following nested routes: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"><span></span></span>
<span class="line"><span>        blog/index.nijor   -&gt; /blog</span></span>
<span class="line"><span>        blog/[slug].nijor  -&gt; /blog/:slug</span></span>
<span class="line"><span>    </span></span></code></pre></code></section><section n-scope="mjsl2"><h1 n-scope="mjsl2">Parameterized (Dynamic) Routing</h1><p n-scope="mjsl2"> Dynamic paths are defined by wrapping a parameter name in square brackets <span class="txt" n-scope="mjsl2">[paramName]</span> inside the filename. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"><span></span></span>
<span class="line"><span>        src/pages/products/[id]/[name].nijor</span></span>
<span class="line"><span>    </span></span></code></pre></code><p n-scope="mjsl2"> This route matches dynamic paths such as <span class="txt" n-scope="mjsl2">/products/123/phone</span>. Dynamic parameters are made available to the page through the <span class="txt" n-scope="mjsl2">params</span> attribute in the <span class="txt" n-scope="mjsl2">&lt;template&gt;</span> block (unlike components which use props). </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#9CDCFE"> params</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{ id, name }"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Product: \{name}</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">p</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Product ID: \{id}</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">p</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">button</span><span style="color:#9CDCFE"> on:click</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"buy('\{id}')"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Purchase {name}</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">button</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#C586C0">            export</span><span style="color:#569CD6"> function</span><span style="color:#DCDCAA"> buy</span><span style="color:#D4D4D4">(</span><span style="color:#9CDCFE">id</span><span style="color:#D4D4D4">) {</span></span>
<span class="line"><span style="color:#DCDCAA">                alert</span><span style="color:#D4D4D4">(</span><span style="color:#CE9178">"Purchasing product: "</span><span style="color:#D4D4D4"> + </span><span style="color:#9CDCFE">id</span><span style="color:#D4D4D4">);</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="mjsl2"> Route parameters can be accessed directly in the template and are available inside your <span class="txt" n-scope="mjsl2">&lt;script&gt;</span> scope. However, do not reference route parameters directly inside inline event function signatures; instead, pass them as arguments explicitly. </p></section><section n-scope="mjsl2"><h1 n-scope="mjsl2">Layouts</h1><p n-scope="mjsl2"> Layouts define the shared, structural shell used across different pages. Common layout elements include navigation bars, sidebars, headers, and footers. </p><p n-scope="mjsl2"> Layouts are stored in the <span class="txt" n-scope="mjsl2">src/layouts</span> folder. Every Nijor application must have a default layout at <span class="txt" n-scope="mjsl2">src/layouts/default.nijor</span>, which wraps every page by default. </p><p n-scope="mjsl2"> Layouts identify where the dynamic page content should be injected using the special <span class="txt" n-scope="mjsl2">n:slot</span> attribute. </p><h3 n-scope="mjsl2">Example Layout : <span class="txt" n-scope="mjsl2">src/layouts/default.nijor</span></h3> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">nav</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">a</span><span style="color:#9CDCFE"> n:route</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"/"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Home</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">a</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6"> | </span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">a</span><span style="color:#9CDCFE"> nroute</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"/about"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">About Us</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">a</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;/</span><span style="color:#569CD6">nav</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#6A9955">            &lt;!-- Page content is loaded inside the slot below --&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">div</span><span style="color:#9CDCFE"> n:slot</span><span style="color:#808080">&gt;&lt;/</span><span style="color:#569CD6">div</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="mjsl2"> A page can specify a custom layout by adding the <span class="txt" n-scope="mjsl2">layout</span> attribute to its <span class="txt" n-scope="mjsl2">&lt;template&gt;</span>: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#9CDCFE"> layout</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"dashboard"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Welcome to the Admin Portal</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="mjsl2"> This snippet instructs Nijor to render the page inside <span class="txt" n-scope="mjsl2">src/layouts/dashboard.nijor</span>. If the layout attribute is omitted, Nijor defaults back to <span class="txt" n-scope="mjsl2">default.nijor</span>. </p></section><section n-scope="mjsl2"><h1 n-scope="mjsl2">Client-Side Navigation</h1><p n-scope="mjsl2"> To enable smooth, single-page application (SPA) transitions without reloading the page, use the <span class="txt" n-scope="mjsl2">n:route</span> attribute on your anchor tags. Standard <span class="txt" n-scope="mjsl2">href</span> attributes still work, but they trigger a full browser page refresh. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">a</span><span style="color:#9CDCFE"> n:route</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"/dashboard"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Dashboard</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">a</span><span style="color:#808080">&gt;</span><span style="color:#6A9955"> &lt;!-- Smooth SPA client-side navigation --&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">a</span><span style="color:#9CDCFE"> href</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"/dashboard"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Dashboard</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">a</span><span style="color:#808080">&gt;</span><span style="color:#6A9955">  &lt;!-- Triggers full browser refresh --&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="mjsl2"> Use <span class="txt" n-scope="mjsl2">n:route</span> for internal paths, and stick to standard <span class="txt" n-scope="mjsl2">href</span> for external websites. </p></section><section n-scope="mjsl2"><h1 n-scope="mjsl2">Link Prefetching</h1><p n-scope="mjsl2"> Nijor automatically prefetches visible route links on the viewport to optimize page transition performance. When a link featuring <span class="txt" n-scope="mjsl2">n:route</span> enters the user's viewport, its route bundles are loaded in the background, making transitions nearly instantaneous when clicked. </p><p n-scope="mjsl2"> If a route loads extensive datasets or you want to save network bandwidth, you can opt-out of prefetching for specific links using the <span class="txt" n-scope="mjsl2">no-prefetch</span> attribute: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">a</span><span style="color:#9CDCFE"> n:route</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"/heavy-dashboard"</span><span style="color:#9CDCFE"> no-prefetch</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Admin Dashboard</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">a</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code></section><section n-scope="mjsl2"><h1 n-scope="mjsl2">Route Lifecycle : <span class="txt" n-scope="mjsl2">onRoute</span></h1><p n-scope="mjsl2"> Nijor provides an <span class="txt" n-scope="mjsl2">onRoute()</span> lifecycle hook to execute code whenever a client-side navigation occurs. This callback is ideal for tracking analytics, triggering page-view side effects, or updating global application state. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">onRoute</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/router"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#DCDCAA">        onRoute</span><span style="color:#E6E6E6">(</span><span style="color:#9CDCFE">route</span><span style="color:#569CD6"> =&gt;</span><span style="color:#E6E6E6"> {</span></span>
<span class="line"><span style="color:#9CDCFE">            console</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">log</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">"Navigated to: "</span><span style="color:#D4D4D4"> +</span><span style="color:#9CDCFE"> route</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#6A9955">            // e.g., trigger Google Analytics page views</span></span>
<span class="line"><span style="color:#E6E6E6">        });</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code></section><section n-scope="mjsl2"><h1 n-scope="mjsl2">Page Metadata &amp; Head Tag</h1><p n-scope="mjsl2"> Nijor pages can feature a custom <span class="txt" n-scope="mjsl2">&lt;head&gt;</span> block (using the <span class="txt" n-scope="mjsl2">&lt;nhead&gt;</span> tag inside code templates) to manage page-specific metadata such as titles, keywords, and description tags. </p><p n-scope="mjsl2"> The title metadata operates dynamically in both client-side rendering (CSR) and server-side rendering (SSR), and supports route parameters: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">head</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">title</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">{name} | Store</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">title</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">meta</span><span style="color:#9CDCFE"> name</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"description"</span><span style="color:#9CDCFE"> content</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"Explore ${name} specifications."</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">head</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#9CDCFE"> params</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{ id, name }"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Product: {name}</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">p</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">ID: {id}</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">p</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code></section><section n-scope="mjsl2"><h1 n-scope="mjsl2">Advanced : Understanding App.js</h1><p n-scope="mjsl2"> The file <span class="txt" n-scope="mjsl2">src/App.js</span> is the official entry point of a Nijor web application. Nijor is versatile: you can run a Nijor app both with or without routing. </p><h2 n-scope="mjsl2">(1) Standard Setup with Routing</h2><p n-scope="mjsl2"> When utilizing file-based routing, <span class="txt" n-scope="mjsl2">App.js</span> initializes the router and includes the compiler-utilized <span class="txt" n-scope="mjsl2">//@Routes()</span> directive, which dynamically injects pages and layouts at compile time. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">Render</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/core"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#CE9178"> "nijor/router"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#6A9955">        //@Routes()</span></span>
<span class="line"></span>
<span class="line"><span style="color:#E6E6E6">        (</span><span style="color:#569CD6">async</span><span style="color:#E6E6E6"> () </span><span style="color:#569CD6">=&gt;</span><span style="color:#C586C0"> await</span><span style="color:#DCDCAA"> Render</span><span style="color:#E6E6E6">(</span><span style="color:#9CDCFE">document</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">getElementById</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">'app'</span><span style="color:#E6E6E6">)))();</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><h2 n-scope="mjsl2">(2) Advanced Routing with <span class="txt" n-scope="mjsl2">App.nijor</span></h2><p n-scope="mjsl2"> If you want your layouts to share persistent components (such as a global header, floating side panel, or theme toggler), you can register a root component called <span class="txt" n-scope="mjsl2">App.nijor</span>. </p><p n-scope="mjsl2"> Replace <span class="txt" n-scope="mjsl2">&lt;div id="app"&gt;&lt;/div&gt;</span> inside your <span class="txt" n-scope="mjsl2">index.html</span> with <span class="txt" n-scope="mjsl2">&lt;app&gt;&lt;/app&gt;</span>, and configure <span class="txt" n-scope="mjsl2">App.js</span> as follows : </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">Render</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/core"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#CE9178"> "nijor/router"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#9CDCFE"> App</span><span style="color:#C586C0"> from</span><span style="color:#CE9178"> "@/App.nijor"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#6A9955">        //@Routes()</span></span>
<span class="line"></span>
<span class="line"><span style="color:#E6E6E6">        (</span><span style="color:#569CD6">async</span><span style="color:#E6E6E6"> () </span><span style="color:#569CD6">=&gt;</span><span style="color:#E6E6E6"> {</span></span>
<span class="line"><span style="color:#C586C0">            await</span><span style="color:#9CDCFE"> App</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">run</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">'app'</span><span style="color:#E6E6E6">, </span><span style="color:#B5CEA8">1</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#C586C0">            await</span><span style="color:#DCDCAA"> Render</span><span style="color:#E6E6E6">(</span><span style="color:#9CDCFE">document</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">getElementById</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">'app'</span><span style="color:#E6E6E6">)) </span><span style="color:#6A9955">// Move &lt;div id="app"&gt;&lt;/div&gt; inside App.nijor</span></span>
<span class="line"><span style="color:#E6E6E6">        })();</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><h2 n-scope="mjsl2">(3) Setup Without Routing</h2><p n-scope="mjsl2"> For single-page applications or simple widgets that do not require navigation, you can bypass the router entirely. Replace <span class="txt" n-scope="mjsl2">&lt;div id="app"&gt;&lt;/div&gt;</span> in your <span class="txt" n-scope="mjsl2">index.html</span> with <span class="txt" n-scope="mjsl2">&lt;app&gt;&lt;/app&gt;</span>, and bootstrap your root component directly: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#9CDCFE"> App</span><span style="color:#C586C0"> from</span><span style="color:#CE9178"> "@/App.nijor"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#E6E6E6">        (</span><span style="color:#569CD6">async</span><span style="color:#E6E6E6"> () </span><span style="color:#569CD6">=&gt;</span><span style="color:#C586C0"> await</span><span style="color:#9CDCFE"> App</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">run</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">'app'</span><span style="color:#E6E6E6">, </span><span style="color:#B5CEA8">1</span><span style="color:#E6E6E6">))();</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><h2 n-scope="mjsl2">Component Bootstrapping Mechanics</h2><p n-scope="mjsl2"> Every compiled Nijor component exposes a native <span class="txt" n-scope="mjsl2">run()</span> method. The <span class="txt" n-scope="mjsl2">run</span> function targets and initializes elements by their tags: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#9CDCFE">        Component</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">run</span><span style="color:#E6E6E6">(</span><span style="color:#9CDCFE">tagName</span><span style="color:#E6E6E6">, </span><span style="color:#9CDCFE">count</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="mjsl2"> The <span class="txt" n-scope="mjsl2">tagName</span> defines which element is targetable, and <span class="txt" n-scope="mjsl2">count</span> determines how many matching DOM occurrences should be swapped out. Under normal development circumstances, the Nijor compiler handles this bootstrapping sequence automatically. </p></section>`},`docs`);export{t as default};