import{a as e}from"../main.js";const t=new e(async function({},e){return document.title=`Quick Start | Nijor`,`<section n-scope="vlhsq"><h1 n-scope="vlhsq">Quick Start Guide</h1><p n-scope="vlhsq"> Welcome to Nijor! This guide will help you set up, run, and build your very first Nijor web application in just a few minutes. </p><h2 n-scope="vlhsq">1. Scaffold a New Project</h2><p n-scope="vlhsq"> You can quickly create a pre-configured project structure using our CLI tool. Choose your preferred package manager to run the initializer: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#DCDCAA">            npx</span><span style="color:#CE9178"> create-nijor-app</span><span style="color:#CE9178"> my-app</span></span>
<span class="line"><span style="color:#E6E6E6">        </span></span></code></pre></code><p n-scope="vlhsq">If you prefer using Bun for faster performance, you can use:</p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#DCDCAA">            bunx</span><span style="color:#CE9178"> create-nijor-app</span><span style="color:#CE9178"> my-app</span></span>
<span class="line"><span style="color:#E6E6E6">        </span></span></code></pre></code><h2 n-scope="vlhsq">2. Start the Development Server</h2><p n-scope="vlhsq"> Navigate to your new project directory and spin up the local development server. Nijor uses Bun to deliver an exceptionally fast development cycle: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#DCDCAA">            cd</span><span style="color:#CE9178"> my-app</span></span>
<span class="line"><span style="color:#DCDCAA">            bun</span><span style="color:#CE9178"> run</span><span style="color:#CE9178"> dev</span></span>
<span class="line"><span style="color:#E6E6E6">        </span></span></code></pre></code><p n-scope="vlhsq"> Once started, the development server will be active at <span class="txt" n-scope="vlhsq">http://localhost:3000</span> with <span class="txt" n-scope="vlhsq">live reload</span> fully enabled. Any changes you make to your components or routes will instantly reflect in the browser. You can customize the server port and reload settings inside the <span class="txt" n-scope="vlhsq">nijor.config.js</span> file. </p><h2 n-scope="vlhsq">3. Build for Production</h2><p n-scope="vlhsq"> When your application is ready to be deployed, generate an optimized production build using the following command: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#DCDCAA">            bun</span><span style="color:#CE9178"> run</span><span style="color:#CE9178"> build</span></span>
<span class="line"><span style="color:#E6E6E6">        </span></span></code></pre></code><p n-scope="vlhsq"> This command triggers the Nijor compiler to analyze your routes, bundle your static assets, compile your scoped styling, and output a highly optimized, production-ready version of your app. </p><h2 n-scope="vlhsq">Next Steps</h2><p n-scope="vlhsq"> Now that your local environment is running, dive into <a nroute="/docs/components" n-scope="vlhsq">Components</a> to see how to build user interfaces, or explore <a nroute="/docs/routing" n-scope="vlhsq">Routing</a> to understand file-based page organization in Nijor! </p></section>`},`docs`);export{t as default};