import{a as e}from"../main.js";const t=new e(async function({},e){return document.title=`Styles | Nijor`,`<section n-scope="k5m5uw"><h1 n-scope="k5m5uw">Styling &amp; Themes</h1><p n-scope="k5m5uw"> Nijor offers elegant support for styling. By default, styles defined inside a component are fully scoped, meaning they only apply to the HTML elements declared within that component. </p><p n-scope="k5m5uw"> In addition to scoped styles, Nijor includes native support for dark mode, multiple custom themes, reactive class binding, and PostCSS integration out of the box. </p></section><section n-scope="k5m5uw"><h1 n-scope="k5m5uw">Component Theming</h1><p n-scope="k5m5uw"> Modern applications frequently require multi-theme support (e.g., Light, Dark, or Dim modes). While standard CSS media queries are effective, they are bound to the operating system's settings. </p><p n-scope="k5m5uw"> Nijor solves this by providing the <span class="txt" n-scope="k5m5uw">theme</span> attribute on <span class="txt" n-scope="k5m5uw">&lt;style&gt;</span> (or <span class="txt" n-scope="k5m5uw">&lt;nstyle&gt;</span> in templates) blocks. An unthemed style block represents the base or default theme. Themed style blocks override specific properties when their target theme is activated. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">div</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Theme Explorer</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;/</span><span style="color:#569CD6">div</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#6A9955">            /* Base (Default/Light) Theme Styles */</span></span>
<span class="line"><span style="color:#D7BA7D">            div</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                margin</span><span style="color:#D4D4D4">: </span><span style="color:#B5CEA8">10px</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#9CDCFE">                padding</span><span style="color:#D4D4D4">: </span><span style="color:#B5CEA8">16px</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#9CDCFE">                background-color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">#ffffff</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#9CDCFE">                border</span><span style="color:#D4D4D4">: </span><span style="color:#B5CEA8">1px</span><span style="color:#CE9178"> solid</span><span style="color:#CE9178"> #ddd</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D7BA7D">            h1</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">#333333</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">style</span><span style="color:#9CDCFE"> theme</span><span style="color:#D4D4D4">=</span><span style="color:#CE9178">"dark"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#6A9955">            /* Scoped Dark Theme Overrides */</span></span>
<span class="line"><span style="color:#D7BA7D">            div</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                background-color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">#121212</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#9CDCFE">                border-color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">#333333</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D7BA7D">            h1</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">#ffffff</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">style</span><span style="color:#9CDCFE"> theme</span><span style="color:#D4D4D4">=</span><span style="color:#CE9178">"dim"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#6A9955">            /* Scoped Dim Theme Overrides */</span></span>
<span class="line"><span style="color:#D7BA7D">            div</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                background-color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">#2c3e50</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#9CDCFE">                border-color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">#34495e</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D7BA7D">            h1</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">#ecf0f1</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code></section><section n-scope="k5m5uw"><h1 n-scope="k5m5uw">Managing Active Themes</h1><p n-scope="k5m5uw"> The built-in <span class="txt" n-scope="k5m5uw">nijor/theme</span> module makes controlling active themes incredibly simple. It exports two main helper functions: <span class="txt" n-scope="k5m5uw">autoTheme()</span> and <span class="txt" n-scope="k5m5uw">setTheme()</span>. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">autoTheme</span><span style="color:#E6E6E6">, </span><span style="color:#9CDCFE">setTheme</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/theme"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><h2 n-scope="k5m5uw">1. Automatic Theme Control</h2><p n-scope="k5m5uw"> Call <span class="txt" n-scope="k5m5uw">autoTheme()</span> to automatically match the application theme to the user's system preference. If their OS is set to dark mode, Nijor applies the style rules defined under <span class="txt" n-scope="k5m5uw">theme="dark"</span>; otherwise, it falls back to the base styles. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">autoTheme</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/theme"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#6A9955">        // Call during application bootstrap (e.g., in App.js)</span></span>
<span class="line"><span style="color:#DCDCAA">        autoTheme</span><span style="color:#E6E6E6">();</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><h2 n-scope="k5m5uw">2. Manual Theme Toggling</h2><p n-scope="k5m5uw"> Use <span class="txt" n-scope="k5m5uw">setTheme()</span> to programmatically switch themes. This overrides automatic detection and lets you toggle custom themes dynamically: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">setTheme</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/theme"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#DCDCAA">        setTheme</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">"dark"</span><span style="color:#E6E6E6">);   </span><span style="color:#6A9955">// Activate dark theme overrides</span></span>
<span class="line"><span style="color:#DCDCAA">        setTheme</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">"dim"</span><span style="color:#E6E6E6">);    </span><span style="color:#6A9955">// Activate dim theme overrides</span></span>
<span class="line"><span style="color:#DCDCAA">        setTheme</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">"light"</span><span style="color:#E6E6E6">);  </span><span style="color:#6A9955">// Force base theme (bypassing auto-detection)</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="k5m5uw"> To restore system-level automatic theme detection, simply pass <span class="txt" n-scope="k5m5uw">"auto"</span>: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#DCDCAA">            setTheme</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">"auto"</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#E6E6E6">        </span></span></code></pre></code><h2 n-scope="k5m5uw">3. Theme Persistence</h2><p n-scope="k5m5uw"> Nijor automatically stores the currently active theme in the browser's local storage. This ensures the user's preference persists across page loads. You can read the active selection using: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#569CD6">        const</span><span style="color:#9CDCFE"> currentTheme</span><span style="color:#D4D4D4"> =</span><span style="color:#9CDCFE"> window</span><span style="color:#E6E6E6">.</span><span style="color:#9CDCFE">localStorage</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">getItem</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">"theme"</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code></section><section n-scope="k5m5uw"><h1 n-scope="k5m5uw">Conditional Classes</h1><p n-scope="k5m5uw"> Nijor provides a elegant syntax to apply CSS classes conditionally using the <span class="txt" n-scope="k5m5uw">class:classname</span> attribute. A class is added to the element if the expression inside curly braces evaluates to a truthy value; otherwise, it is omitted. </p><h3 n-scope="k5m5uw">Static Conditional Example</h3> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">button</span><span style="color:#9CDCFE"> class:active</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{isActive}"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Save Changes</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">button</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#569CD6">            const</span><span style="color:#9CDCFE"> isActive</span><span style="color:#D4D4D4"> = </span><span style="color:#569CD6">true</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#D7BA7D">            .active</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">#007bff</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#9CDCFE">                font-weight</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">bold</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><h3 n-scope="k5m5uw">Reactive Conditional Example</h3><p n-scope="k5m5uw"> This syntax integrates with Nijor's reactive state variables, allowing you to add and remove classes dynamically in response to state transitions. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">button</span><span style="color:#9CDCFE"> class:enabled</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{$.enabled}"</span><span style="color:#9CDCFE"> on:click</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"toggle()"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Toggle Power</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">button</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#9CDCFE">            $</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">enabled</span><span style="color:#D4D4D4"> = </span><span style="color:#569CD6">false</span><span style="color:#D4D4D4">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#C586C0">            export</span><span style="color:#569CD6"> function</span><span style="color:#DCDCAA"> toggle</span><span style="color:#D4D4D4">(</span><span style="color:#9CDCFE">$</span><span style="color:#D4D4D4">) {</span></span>
<span class="line"><span style="color:#9CDCFE">                $</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">enabled</span><span style="color:#D4D4D4"> = !</span><span style="color:#9CDCFE">$</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">enabled</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#D7BA7D">            .enabled</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                background-color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">#28a745</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#9CDCFE">                color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">white</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code></section><section n-scope="k5m5uw"><h1 n-scope="k5m5uw">CSS Processing: PostCSS &amp; Tailwind CSS</h1><p n-scope="k5m5uw"> Nijor features an integrated PostCSS architecture to process application stylesheets during the build step. You can extend this processing by registering plugins inside your project's <span class="txt" n-scope="k5m5uw">postcss.config.mjs</span> file. </p><p n-scope="k5m5uw"> By default, Nijor pre-configures and runs the following PostCSS plugins to keep your bundles optimized and modern: </p><p n-scope="k5m5uw"><span class="txt" n-scope="k5m5uw">postcss-nested</span>: Write clean, nested style declarations.</p><p n-scope="k5m5uw"><span class="txt" n-scope="k5m5uw">autoprefixer</span>: Automatically add CSS vendor prefixes for broad browser compatibility.</p><p n-scope="k5m5uw"><span class="txt" n-scope="k5m5uw">cssnano</span>: Minify and compress compiled production CSS.</p><p n-scope="k5m5uw"><strong n-scope="k5m5uw">Tailwind CSS Integration:</strong> Because Nijor compiles using standard PostCSS, integrating Tailwind CSS is extremely straightforward. Simply install Tailwind via Bun/NPM, add it as a plugin in your <span class="txt" n-scope="k5m5uw">postcss.config.mjs</span>, and define your content paths to scan <span class="txt" n-scope="k5m5uw">*.nijor</span> files. </p></section>`},`docs`);export{t as default};