import{t as e}from"../page-lNBJ.js";const t=new e(async function({},e){return document.title=`Routing | Nijor`,`<section n-scope="zn2v"><h1 n-scope="zn2v">Routing</h1><p n-scope="zn2v"> Nijor uses file-based routing. Routes are automatically generated from the files inside the <span class="txt" n-scope="zn2v">src/pages</span> directory. Each <span class="txt" n-scope="zn2v">.nijor</span> file inside this directory becomes a route in your application. This approach removes the need to manually configure routes. </p></section><section n-scope="zn2v"><h1 n-scope="zn2v">Understanding App.js</h1><p n-scope="zn2v"><span class="txt" n-scope="zn2v">src/App.js</span> is the entry point of a Nijor application. It is not limited to routing. Nijor applications can also be written without using the router. </p><h2 n-scope="zn2v">Without Routing</h2><p n-scope="zn2v"> If your application does not use routing, you can directly run a Nijor component from <span class="txt" n-scope="zn2v">App.js</span>. In that case, replace <span class="txt" n-scope="zn2v">&lt;div id="app"&gt;&lt;/div&gt;</span> in <span class="txt" n-scope="zn2v">index.html</span> with <span class="txt" n-scope="zn2v">&lt;app&gt;&lt;/app&gt;</span>. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#9CDCFE"> App</span><span style="color:#C586C0"> from</span><span style="color:#CE9178"> "@/App.nijor"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#E6E6E6">        (</span><span style="color:#569CD6">async</span><span style="color:#E6E6E6"> () </span><span style="color:#569CD6">=&gt;</span><span style="color:#C586C0"> await</span><span style="color:#9CDCFE"> App</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">run</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">'app'</span><span style="color:#E6E6E6">, </span><span style="color:#B5CEA8">1</span><span style="color:#E6E6E6">))();</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="zn2v"> In this example, the <span class="txt" n-scope="zn2v">App</span> component is rendered directly and all other components are rendered inside the App component. </p><h2 n-scope="zn2v">How Components Run</h2><p n-scope="zn2v"> Internally, all Nijor components are rendered in this way. Every compiled Nijor component exposes a <span class="txt" n-scope="zn2v">run()</span> method. </p><p n-scope="zn2v"> The <span class="txt" n-scope="zn2v">run()</span> method takes two arguments: </p><p n-scope="zn2v"><span class="txt" n-scope="zn2v">name</span> is the component name to target, and <span class="txt" n-scope="zn2v">num</span> specifies how many matching elements should be replaced. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#9CDCFE">        Component</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">run</span><span style="color:#E6E6E6">(</span><span style="color:#9CDCFE">name</span><span style="color:#E6E6E6">, </span><span style="color:#9CDCFE">num</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="zn2v"> The <span class="txt" n-scope="zn2v">name</span> argument exists because the same component can be imported into different pages using different names. <br n-scope="zn2v"> The <span class="txt" n-scope="zn2v">num</span> argument tells Nijor how many occurrences of that component should be replaced. <br n-scope="zn2v"></p><p n-scope="zn2v"> In normal application development, you usually do not need to work with these details directly. They are handled internally by the compiler. </p><h2 n-scope="zn2v">With Routing</h2><p n-scope="zn2v"> When routing is enabled, <span class="txt" n-scope="zn2v">App.js</span> also initializes the router and provides a place for the compiler to inject route and layout definitions. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">Render</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/core"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#CE9178"> "nijor/router"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#6A9955">        //@Routes()</span></span>
<span class="line"></span>
<span class="line"><span style="color:#E6E6E6">        (</span><span style="color:#569CD6">async</span><span style="color:#E6E6E6"> () </span><span style="color:#569CD6">=&gt;</span><span style="color:#C586C0"> await</span><span style="color:#DCDCAA"> Render</span><span style="color:#E6E6E6">(</span><span style="color:#9CDCFE">document</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">getElementById</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">'app'</span><span style="color:#E6E6E6">)))();</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="zn2v"> The <span class="txt" n-scope="zn2v">//@Routes()</span> comment is used by the compiler. During compilation, it is replaced with the generated route and layout definitions. </p><h2 n-scope="zn2v">Using App.nijor with Routing</h2><p n-scope="zn2v"> If you want all layouts to share common components, you can create <span class="txt" n-scope="zn2v">App.nijor</span> and use it as the root component of the application. </p><p n-scope="zn2v"> In that case, replace <span class="txt" n-scope="zn2v">&lt;div id="app"&gt;&lt;/div&gt;</span> in <span class="txt" n-scope="zn2v">index.html</span> with <span class="txt" n-scope="zn2v">&lt;app&gt;&lt;/app&gt;</span>. </p><p n-scope="zn2v"> Then <span class="txt" n-scope="zn2v">App.js</span> will look like this: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">Render</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/core"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#CE9178"> "nijor/router"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#9CDCFE"> App</span><span style="color:#C586C0"> from</span><span style="color:#CE9178"> "@/App.nijor"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#6A9955">        //@Routes()</span></span>
<span class="line"></span>
<span class="line"><span style="color:#E6E6E6">        (</span><span style="color:#569CD6">async</span><span style="color:#E6E6E6"> () </span><span style="color:#569CD6">=&gt;</span><span style="color:#E6E6E6"> {</span></span>
<span class="line"><span style="color:#C586C0">            await</span><span style="color:#9CDCFE"> App</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">run</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">'app'</span><span style="color:#E6E6E6">, </span><span style="color:#B5CEA8">1</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#C586C0">            await</span><span style="color:#DCDCAA"> Render</span><span style="color:#E6E6E6">(</span><span style="color:#9CDCFE">document</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">getElementById</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">'app'</span><span style="color:#E6E6E6">));</span></span>
<span class="line"><span style="color:#E6E6E6">        })();</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="zn2v"> In this setup, <span class="txt" n-scope="zn2v">App.nijor</span> is rendered first, and the router then renders layouts and pages inside the <span class="txt" n-scope="zn2v">#app</span> element defined inside it. </p></section><section n-scope="zn2v"><h1 n-scope="zn2v">Layouts</h1><p n-scope="zn2v"> Layouts define the shared structure used by pages. Common layout elements include navigation bars, headers, sidebars, footers. Layouts are stored inside <span class="txt" n-scope="zn2v">src/layouts</span>. Every project must contain a default layout <span class="txt" n-scope="zn2v">src/layouts/default.nijor</span> because every page is rendered inside a layout. </p><p n-scope="zn2v"> Layouts use the special attribute <span class="txt" n-scope="zn2v">n:slot</span> to determine where page content should be rendered. You shouldn't add id to these elements. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">nav</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">a</span><span style="color:#9CDCFE"> n:route</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"/"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Home</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">a</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">a</span><span style="color:#9CDCFE"> n:route</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"/about"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">About</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">a</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;/</span><span style="color:#569CD6">nav</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">div</span><span style="color:#9CDCFE"> n:slot</span><span style="color:#808080">&gt;&lt;/</span><span style="color:#569CD6">div</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="zn2v"> Pages can specify which layout they should use using the <span class="txt" n-scope="zn2v">layout</span> attribute on the <span class="txt" n-scope="zn2v">body</span> element. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#9CDCFE"> layout</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"dashboard"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Dashboard</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="zn2v"> This will use the layout file <span class="txt" n-scope="zn2v">src/layouts/dashboard.nijor</span>. If the layout attribute is not defined, Nijor will automatically use <span class="txt" n-scope="zn2v">src/layouts/default.nijor</span>. </p></section><section n-scope="zn2v"><h1 n-scope="zn2v">Basic Routing</h1><p n-scope="zn2v"> Every file inside <span class="txt" n-scope="zn2v">src/pages</span> becomes a route. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"><span></span></span>
<span class="line"><span>        src/pages/</span></span>
<span class="line"><span>            index.nijor</span></span>
<span class="line"><span>            about.nijor</span></span>
<span class="line"><span>    </span></span></code></pre></code><p n-scope="zn2v"> This generates the following routes: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"><span></span></span>
<span class="line"><span>        index.nijor  -&gt; /</span></span>
<span class="line"><span>        about.nijor  -&gt; /about</span></span>
<span class="line"><span>    </span></span></code></pre></code><p n-scope="zn2v"> If a route does not exist, Nijor renders <span class="txt" n-scope="zn2v">src/pages/404.nijor</span>. </p></section><section n-scope="zn2v"><h1 n-scope="zn2v">Nested Routes</h1><p n-scope="zn2v"> Folders inside <span class="txt" n-scope="zn2v">src/pages</span> create nested routes. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"><span></span></span>
<span class="line"><span>        src/pages/</span></span>
<span class="line"><span>            blog/</span></span>
<span class="line"><span>                index.nijor</span></span>
<span class="line"><span>                [slug].nijor</span></span>
<span class="line"><span>    </span></span></code></pre></code><p n-scope="zn2v"> This generates the following routes: </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"><span></span></span>
<span class="line"><span>        blog/index.nijor   -&gt; /blog</span></span>
<span class="line"><span>        blog/[slug].nijor  -&gt; /blog/:slug</span></span>
<span class="line"><span>    </span></span></code></pre></code></section><section n-scope="zn2v"><h1 n-scope="zn2v">Parameterized Routing</h1><p n-scope="zn2v"> Nijor supports parameterized routing. A dynamic route is created by wrapping the parameter name in square brackets in the file name. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"><span></span></span>
<span class="line"><span>        src/pages/products/[id]/[name].nijor</span></span>
<span class="line"><span>    </span></span></code></pre></code><p n-scope="zn2v"> This route can match paths like <span class="txt" n-scope="zn2v">/products/42/laptop</span>. Pages receive route parameters through <span class="txt" n-scope="zn2v">params</span> instead of props. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#9CDCFE"> params</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{ id, name }"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">{name}</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">button</span><span style="color:#9CDCFE"> on:click</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"buy('\{id}')"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Buy {name}</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">button</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#569CD6">            function</span><span style="color:#DCDCAA"> buy</span><span style="color:#D4D4D4">(</span><span style="color:#9CDCFE">id</span><span style="color:#D4D4D4">) {</span></span>
<span class="line"><span style="color:#6A9955">                // API calls</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="zn2v"> Route parameters can be used directly inside <span class="txt" n-scope="zn2v">script</span> just like other variables. However, route parameters should not be referenced directly inside inline event function calls. </p></section><section n-scope="zn2v"><h1 n-scope="zn2v">onRoute</h1><p n-scope="zn2v">Nijor provides an <span class="txt" n-scope="zn2v">onRoute()</span> helper for running code whenever the current route changes.</p><p n-scope="zn2v"> The callback receives the current route as its argument. This can be useful for analytics, route-based side effects, or logic that should run after navigation. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">onRoute</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/router"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#DCDCAA">        onRoute</span><span style="color:#E6E6E6">(</span><span style="color:#9CDCFE">route</span><span style="color:#569CD6"> =&gt;</span><span style="color:#E6E6E6"> { </span><span style="color:#6A9955">/* Do something */</span><span style="color:#E6E6E6">});</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="zn2v">Every time the page route changes, the registered callback runs with the updated route.</p></section><section n-scope="zn2v"><h1 n-scope="zn2v">Navigation</h1><p n-scope="zn2v"> Navigation between routes is done using the <span class="txt" n-scope="zn2v">n:route</span> attribute on anchor tags. The Nijor compiler converts <span class="txt" n-scope="zn2v">n:route</span> links into client-side navigation handlers, allowing pages to change without reloading the browser. Using <span class="txt" n-scope="zn2v">href</span> instead will still work, but it will cause the page to refresh. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">a</span><span style="color:#9CDCFE"> n:route</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"/"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Index Page</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">a</span><span style="color:#808080">&gt;</span><span style="color:#6A9955"> &lt;!--Routing will be smooth ; the page won't refresh--&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">a</span><span style="color:#9CDCFE"> href</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"/"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Index Page</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">a</span><span style="color:#808080">&gt;</span><span style="color:#6A9955"> &lt;!--Routing won't be smooth ; the page will refresh--&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="zn2v"> Use <span class="txt" n-scope="zn2v">n:route</span> for navigation within a Nijor application. Use <span class="txt" n-scope="zn2v">href</span> for external links. </p></section><section n-scope="zn2v"><h1 n-scope="zn2v">Metadata</h1><p n-scope="zn2v"> Pages inside the <span class="txt" n-scope="zn2v">src/pages</span> directory can include a <span class="txt" n-scope="zn2v">head</span> tag. This tag is used for page metadata such as the document title and meta tags. </p><p n-scope="zn2v"> The <span class="txt" n-scope="zn2v">title</span> defined inside <span class="txt" n-scope="zn2v">head</span> works in both CSR and SSR. Other metadata written inside <span class="txt" n-scope="zn2v">head</span> is mainly used during SSR. </p><p n-scope="zn2v">Route parameters can also be used inside the <span class="txt" n-scope="zn2v">head</span> tag.</p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">head</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">title</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">{name} | Product</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">title</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">meta</span><span style="color:#9CDCFE"> name</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"description"</span><span style="color:#9CDCFE"> content</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"Buy ${name} from our store"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">head</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#9CDCFE"> params</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{ id, name }"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">section</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">{name}</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">p</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Product ID: {id}</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">p</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;/</span><span style="color:#569CD6">section</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="zn2v"> In client-side rendering, Nijor uses the page title from the <span class="txt" n-scope="zn2v">head</span> tag. Other metadata is primarily useful when server-side rendering is enabled. </p></section>`},async function({},e){},`docs`);export{t as default};