import{t as e}from"../page-XqH.js";const t=new e(async function({},e){return document.title=`Styles`,`<section n-scope="7p6du"><h1 n-scope="7p6du">Themes</h1><p n-scope="7p6du"> Dark mode is common in modern applications. While it can be implemented using CSS media queries, that approach only works when the browser or operating system theme is already set to dark. </p><p n-scope="7p6du"> In many applications, users should be able to choose between light mode, dark mode, or automatic mode without changing their browser settings. Nijor provides built-in support for this through theme-aware styles and the <span class="txt" n-scope="7p6du">nijor/theme</span> module. </p><p n-scope="7p6du"> In Nijor, themes are defined using the <span class="txt" n-scope="7p6du">theme</span> attribute on <span class="txt" n-scope="7p6du">style</span> tags. Styles inside an <span class="txt" n-scope="7p6du">style</span> block without a <span class="txt" n-scope="7p6du">theme</span> attribute are applied for all themes and are generally used as the base or light theme. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">div</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Nomoskar</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">h1</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;/</span><span style="color:#569CD6">div</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#D7BA7D">            div</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                margin</span><span style="color:#D4D4D4">: </span><span style="color:#B5CEA8">10px</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#9CDCFE">                padding</span><span style="color:#D4D4D4">: </span><span style="color:#B5CEA8">10px</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#9CDCFE">                background-color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">white</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D7BA7D">            h1</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">black</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">style</span><span style="color:#9CDCFE"> theme</span><span style="color:#D4D4D4">=</span><span style="color:#CE9178">"dark"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#D7BA7D">            div</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                background-color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">black</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D7BA7D">            h1</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">white</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">style</span><span style="color:#9CDCFE"> theme</span><span style="color:#D4D4D4">=</span><span style="color:#CE9178">"dim"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#D7BA7D">            div</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                background-color</span><span style="color:#D4D4D4">: </span><span style="color:#DCDCAA">rgb</span><span style="color:#D4D4D4">(</span><span style="color:#B5CEA8">52</span><span style="color:#D4D4D4">, </span><span style="color:#B5CEA8">74</span><span style="color:#D4D4D4">, </span><span style="color:#B5CEA8">87</span><span style="color:#D4D4D4">);</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D7BA7D">            h1</span><span style="color:#D4D4D4"> {</span></span>
<span class="line"><span style="color:#9CDCFE">                color</span><span style="color:#D4D4D4">: </span><span style="color:#CE9178">white</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="7p6du"> In this example, the unthemed <span class="txt" n-scope="7p6du">style</span> block provides the base styles. The themed style blocks override specific properties when the active theme matches their <span class="txt" n-scope="7p6du">theme</span> value. </p><p n-scope="7p6du"> The <span class="txt" n-scope="7p6du">nijor/theme</span> module provides functions for handling themes in a Nijor application. It exports two functions: <span class="txt" n-scope="7p6du">autoTheme()</span> and <span class="txt" n-scope="7p6du">setTheme()</span>. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">autoTheme</span><span style="color:#E6E6E6">, </span><span style="color:#9CDCFE">setTheme</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/theme"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="7p6du"> The <span class="txt" n-scope="7p6du">autoTheme()</span> function automatically applies the appropriate theme based on the browser or system preference. If the browser is in dark mode, Nijor applies the styles defined in <span class="txt" n-scope="7p6du">&lt;style theme="dark"&gt;</span>. If the browser is in light mode, Nijor uses the default styles. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">autoTheme</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/theme"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#DCDCAA">        autoTheme</span><span style="color:#E6E6E6">();</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="7p6du"> The <span class="txt" n-scope="7p6du">setTheme()</span> function manually sets the active theme. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">setTheme</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/theme"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#DCDCAA">        setTheme</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">"dark"</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#DCDCAA">        setTheme</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">"light"</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#DCDCAA">        setTheme</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">"cherry"</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="7p6du"> Once a theme is set manually, <span class="txt" n-scope="7p6du">autoTheme()</span> no longer controls the theme. To restore automatic theme handling, use <span class="txt" n-scope="7p6du">setTheme("auto")</span>. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#DCDCAA">            setTheme</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">"auto"</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#E6E6E6">        </span></span></code></pre></code><p n-scope="7p6du"> The currently selected theme is stored in <span class="txt" n-scope="7p6du">localStorage</span>. You can read it using : </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#569CD6">        const</span><span style="color:#9CDCFE"> theme</span><span style="color:#D4D4D4"> =</span><span style="color:#9CDCFE"> window</span><span style="color:#E6E6E6">.</span><span style="color:#9CDCFE">localStorage</span><span style="color:#E6E6E6">.</span><span style="color:#DCDCAA">getItem</span><span style="color:#E6E6E6">(</span><span style="color:#CE9178">"theme"</span><span style="color:#E6E6E6">);</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="7p6du"> If no theme has been set manually, this returns <span class="txt" n-scope="7p6du">"auto"</span>. </p><p n-scope="7p6du"> Add the following code to <span class="txt" n-scope="7p6du">App.js</span>. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#C586C0">        import</span><span style="color:#E6E6E6"> { </span><span style="color:#9CDCFE">autoTheme</span><span style="color:#E6E6E6"> } </span><span style="color:#C586C0">from</span><span style="color:#CE9178"> "nijor/theme"</span><span style="color:#E6E6E6">;</span></span>
<span class="line"><span style="color:#DCDCAA">        autoTheme</span><span style="color:#E6E6E6">();</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code></section><section n-scope="7p6du"><h1 n-scope="7p6du">Conditional Classes</h1><p n-scope="7p6du"> Nijor allows classes to be added conditionally using the <span class="txt" n-scope="7p6du">class:classname</span> syntax. This syntax is used as an attribute on an element. </p><p n-scope="7p6du"> If the condition is true, the class is added to the element. If the condition is false, the class is not added. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">button</span><span style="color:#9CDCFE"> class:active</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{isActive}"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Save</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">button</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#569CD6">            const</span><span style="color:#9CDCFE"> isActive</span><span style="color:#D4D4D4"> = </span><span style="color:#569CD6">true</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#D7BA7D">            .active</span><span style="color:#D4D4D4">{</span></span>
<span class="line"><span style="color:#9CDCFE">                color</span><span style="color:#D4D4D4"> : </span><span style="color:#CE9178">#0099ff</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="7p6du"> In this example, the class <span class="txt" n-scope="7p6du">active</span> is added only when <span class="txt" n-scope="7p6du">isActive</span> is true. </p><p n-scope="7p6du"> This also works with reactive variables. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">button</span><span style="color:#9CDCFE"> class:enabled</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{$.enabled}"</span><span style="color:#9CDCFE"> on:click</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"toggle()"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Toggle</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">button</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#9CDCFE">            $</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">enabled</span><span style="color:#D4D4D4"> = </span><span style="color:#569CD6">false</span><span style="color:#D4D4D4">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#569CD6">            function</span><span style="color:#DCDCAA"> toggle</span><span style="color:#D4D4D4">(</span><span style="color:#9CDCFE">$</span><span style="color:#D4D4D4">) {</span></span>
<span class="line"><span style="color:#9CDCFE">                $</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">enabled</span><span style="color:#D4D4D4"> = !</span><span style="color:#9CDCFE">$</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">enabled</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#D7BA7D">            .enabled</span><span style="color:#D4D4D4">{</span></span>
<span class="line"><span style="color:#9CDCFE">                color</span><span style="color:#D4D4D4"> : </span><span style="color:#CE9178">#0099ff</span><span style="color:#D4D4D4">;</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">style</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code><p n-scope="7p6du"> Here, the <span class="txt" n-scope="7p6du">active</span> class is added and removed automatically as the value of <span class="txt" n-scope="7p6du">$.enabled</span> changes. </p></section>`},async function({},e){},`docs`);export{t as default};