import{a as e}from"../main.js";const t=new e(async function({},e){return document.title=`Loops | Nijor`,`<section n-scope="uooms"><h1 n-scope="uooms">List Rendering (Loops)</h1><p n-scope="uooms"> Nijor provides a declarative and highly efficient mechanism to render lists of items or repeated HTML structures using the <span class="txt" n-scope="uooms">n:loop</span> attribute. </p><p n-scope="uooms"> When iterating through data, Nijor expects three core attributes : </p><p n-scope="uooms"><span class="txt" n-scope="uooms">n:loop</span>: Declares that the target element represents a looping template. </p><p n-scope="uooms"><span class="txt" n-scope="uooms">source</span>: Specifies the array variable defined inside your component's script. </p><p n-scope="uooms"><span class="txt" n-scope="uooms">var</span>: Defines the name of the variable to represent the current item in the current iteration. </p></section><section n-scope="uooms"><h1 n-scope="uooms">Basic Loop Example</h1><p n-scope="uooms"> A loop must always be declared on a wrapping parent container element (such as a <span class="txt" n-scope="uooms">&lt;div&gt;</span>, <span class="txt" n-scope="uooms">&lt;ul&gt;</span>, or a custom component container). </p><p n-scope="uooms"><strong n-scope="uooms">Crucial Constraint:</strong> Do not add an <span class="txt" n-scope="uooms">id</span> attribute to the element featuring the <span class="txt" n-scope="uooms">n:loop</span> directive, as Nijor manages the identification of repeated nodes dynamically under the hood. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">import</span><span style="color:#9CDCFE"> name</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"house"</span><span style="color:#9CDCFE"> source</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"@/components/house-card.nijor"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">        </span></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">div</span><span style="color:#9CDCFE"> n:loop</span><span style="color:#9CDCFE"> var</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"house"</span><span style="color:#9CDCFE"> source</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"houses"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">house</span><span style="color:#9CDCFE"> name</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{house.name}"</span><span style="color:#9CDCFE"> rent</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"₹{house.rent}"</span><span style="color:#9CDCFE"> location</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{house.location}"</span><span style="color:#808080">&gt;&lt;/</span><span style="color:#569CD6">house</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;/</span><span style="color:#569CD6">div</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#569CD6">            const</span><span style="color:#9CDCFE"> houses</span><span style="color:#D4D4D4"> = [</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name:</span><span style="color:#CE9178"> "The Sky Mansion"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 62000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Hengrabari, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name:</span><span style="color:#CE9178"> "The Octagon Villa"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 30000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Ganeshguri, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name:</span><span style="color:#CE9178"> "The Dragon Palace"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 45000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Kahilipara, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">            ];</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code></section><section n-scope="uooms"><h1 n-scope="uooms">Rendering with Reactive Lists</h1><p n-scope="uooms"> You can combine loops with reactive state by prefixing the array source with <span class="txt" n-scope="uooms">$.</span>. This allows you to dynamically append, remove, or modify items inside the list, causing the loop to automatically re-render and reflect the updated array. </p> <code><pre class="shiki slack-dark" style="background-color:#222222;color:#E6E6E6" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">import</span><span style="color:#9CDCFE"> name</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"house"</span><span style="color:#9CDCFE"> source</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"@/components/house.nijor"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">        </span></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">div</span><span style="color:#9CDCFE"> n:loop</span><span style="color:#9CDCFE"> var</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"house"</span><span style="color:#9CDCFE"> source</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"$.houses"</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">                &lt;</span><span style="color:#569CD6">house</span><span style="color:#9CDCFE"> name</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{house.name}"</span><span style="color:#9CDCFE"> rent</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"₹{house.rent}"</span><span style="color:#9CDCFE"> location</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"{house.location}"</span><span style="color:#808080">&gt;&lt;/</span><span style="color:#569CD6">house</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;/</span><span style="color:#569CD6">div</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">            &lt;</span><span style="color:#569CD6">button</span><span style="color:#9CDCFE"> on:click</span><span style="color:#E6E6E6">=</span><span style="color:#CE9178">"loadMore()"</span><span style="color:#808080">&gt;</span><span style="color:#E6E6E6">Load More Houses</span><span style="color:#808080">&lt;/</span><span style="color:#569CD6">button</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">body</span><span style="color:#808080">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#808080">        &lt;</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#9CDCFE">            $</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">houses</span><span style="color:#D4D4D4"> = [</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name:</span><span style="color:#CE9178"> "The Sky Mansion"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 62000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Hengrabari, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name:</span><span style="color:#CE9178"> "The Octagon Villa"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 30000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Ganeshguri, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">                { </span><span style="color:#9CDCFE">name:</span><span style="color:#CE9178"> "The Dragon Palace"</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">rent:</span><span style="color:#B5CEA8"> 45000</span><span style="color:#D4D4D4">, </span><span style="color:#9CDCFE">location:</span><span style="color:#CE9178"> "Kahilipara, Guwahati"</span><span style="color:#D4D4D4"> },</span></span>
<span class="line"><span style="color:#D4D4D4">            ];</span></span>
<span class="line"></span>
<span class="line"><span style="color:#C586C0">            export</span><span style="color:#569CD6"> async</span><span style="color:#569CD6"> function</span><span style="color:#DCDCAA"> loadMore</span><span style="color:#D4D4D4">(</span><span style="color:#9CDCFE">$</span><span style="color:#D4D4D4">) {</span></span>
<span class="line"><span style="color:#569CD6">                const</span><span style="color:#9CDCFE"> response</span><span style="color:#D4D4D4"> = </span><span style="color:#C586C0">await</span><span style="color:#DCDCAA"> fetch</span><span style="color:#D4D4D4">(</span><span style="color:#CE9178">'/api/more-houses'</span><span style="color:#D4D4D4">);</span></span>
<span class="line"><span style="color:#569CD6">                const</span><span style="color:#9CDCFE"> nextHouses</span><span style="color:#D4D4D4"> = </span><span style="color:#C586C0">await</span><span style="color:#9CDCFE"> response</span><span style="color:#D4D4D4">.</span><span style="color:#DCDCAA">json</span><span style="color:#D4D4D4">();</span></span>
<span class="line"><span style="color:#D4D4D4">                </span></span>
<span class="line"><span style="color:#6A9955">                // Re-assigning the reactive array triggers a direct template refresh</span></span>
<span class="line"><span style="color:#9CDCFE">                $</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">houses</span><span style="color:#D4D4D4"> = [...</span><span style="color:#9CDCFE">$</span><span style="color:#D4D4D4">.</span><span style="color:#9CDCFE">houses</span><span style="color:#D4D4D4">, ...</span><span style="color:#9CDCFE">nextHouses</span><span style="color:#D4D4D4">];</span></span>
<span class="line"><span style="color:#D4D4D4">            }</span></span>
<span class="line"><span style="color:#808080">        &lt;/</span><span style="color:#569CD6">script</span><span style="color:#808080">&gt;</span></span>
<span class="line"><span style="color:#E6E6E6">    </span></span></code></pre></code></section><section n-scope="uooms"><h1 n-scope="uooms">Loop Performance Characteristics</h1><p n-scope="uooms"> When a reactive loop's array is re-assigned (e.g., using array spreading), Nijor's current rendering system re-evaluates and updates the entire list container template. </p><p n-scope="uooms"> While this ensures robust synchronization between your JavaScript state and the DOM, keep it in mind when rendering extremely large lists (e.g., thousands of items), where optimizing the frequency of array updates will ensure smooth interface rendering. </p></section>`},`docs`);export{t as default};